routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('quote', 'QuoteController'); 

app/Ap_copi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ap_Copi extends Model
{
    protected $table = 'ap_copi';   

    public function state(){
        return $this->belongsTo(State::class);
    }
}

app/Quote.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Quote extends Model
{
    //
    protected $fillable = [
        'title',
        'tvshow',
        'season',
        'content',
      ];
}

app/State.php
<?php

namespace App;
use DB;
use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    protected $table = 'ap_states';   
    
    public function ap_copis(){
        return $this->hasMany(Ap_Copi::class);
    }

    

    public function getAverage(){
        return DB::table('ap_copi')->selectRaw('
        avg(steak) as steak,
        avg(grnd_beef) as grnd_beef, 
        avg(sausage) as sausage, 
        avg(fry_chick) as fry_chick, 
        avg(tuna) as tuna, 
        avg(hgal_milk) as hgal_milk, 
        avg(dozen_eggs) as dozen_eggs, 
        avg(margarine) as margarine, 
        avg(parmesan) as parmesan, 
        avg(potatoes) as potatoes, 
        avg(bananas) as bananas, 
        avg(lettuce) as lettuce, 
        avg(bread) as bread, 
        avg(orange_juice) as orange_juice, 
        avg(coffee) as coffee, 
        avg(sugar) as sugar, 
        avg(cereal) as cereal, 
        avg(sweet_peas) as sweet_peas, 
        avg(cooking_oil) as cooking_oil, 
        avg(frozn_meal) as frozn_meal, 
        avg(frozn_corn) as frozn_corn,  
        avg(potato_chips) as potato_chips,  
        avg(coke) as coke,  
        avg(hmbgr_sand) as hmbgr_sand,  
        avg(pizza) as pizza,  
        avg(2_pc_chick) as 2_pc_chick,  
        avg(beer) as beer,  
        avg(wine) as wine
        ')->where('state_id', '=', $this->id)->get();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/QuoteController.php
<?php

namespace App\Http\Controllers;

use App\Quote;
use Illuminate\Http\Request;
use Redirect;

class QuoteController extends Controller
{
    //
     
    public function index()
    {
        $data['quote'] = Quote::all();
   
        return view('quote.list',$data);
    }

    public function show($id)
    {
    }

    public function create()
    {
        return view('quote.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'tvshow' => 'required',
            'season' => 'required',
            'content' => 'required',
        ]);
   
        Quote::create($request->all());
    
        return Redirect::to('quote')
       ->with('success','Great! Quote created successfully.');
    }
    public function edit($id)
    {   
        $where = array('id' => $id);
        $data['quote_info'] = Quote::where($where)->first();
 
        return view('quote.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'tvshow' => 'required',
            'season' => 'required',
            'content' => 'required',
        ]);
         
        $update = ['tvshow' => $request->tvshow, 'season' => $request->season, 'content' => $request->content];
        Quote::where('id',$id)->update($update);
   
        return Redirect::to('quote')
       ->with('success','Great! Quote updated successfully');
    }

    public function destroy($id)
    {
        Quote::where('id',$id)->delete();
   
        return Redirect::to('quote')->with('success','Quote deleted successfully');
    }
    
}

resources/views/quote/create.blade.php
@extends('quote.layout')
   
@section('content')
 
<div class="row">
    <div class="col-lg-12 mt40">
        <div class="pull-left">
            <h2>Add Quote</h2>
        </div>
    </div>
</div>
    
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    
<form action="{{ route('quote.store') }}" method="POST" name="add_note">
    {{ csrf_field() }}
   
     <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <strong>TV Show</strong>
                <input type="text" name="tvshow" class="form-control" placeholder="Enter Title">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Season</strong>
                <input type="text" name="season" class="form-control" placeholder="Enter Title">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Quote</strong>
                <textarea class="form-control" col="4" name="content" 
                 placeholder="Enter Description"></textarea>
            </div>
        </div>
        <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
    
</form>
@endsection

resources/views/quote/edit.blade.php
@extends('quote.layout')
   
@section('content')
 
<div class="row">
    <div class="col-lg-12 mt40">
        <div class="pull-left">
            <h2>Update Quote</h2>
        </div>
    </div>
</div>
    
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Opps!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
    
<form action="{{ route('quote.update', $quote_info->id) }}" method="POST" name="update_note">
    {{ csrf_field() }}
    @method('PATCH')
   
     <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <strong>TV Show</strong>
                <input type="text" name="tvshow" class="form-control" placeholder="Enter TV show" value="{{ $quote_info->tvshow }}">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Season</strong>
                <input type="text" name="season" class="form-control" placeholder="Enter Season" value="{{ $quote_info->season }}">
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <strong>Content</strong>
                <textarea class="form-control" col="4" name="content" placeholder="Enter Description" >{{ $quote_info->content }}</textarea>
            </div>
        </div>
        <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
    
</form>
@endsection

resources/views/quote/layout.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Favorite Quotes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .mt40{
            margin-top: 40px;
        }
    </style>
</head>
<body>
   
<div class="container">
    @yield('content')
</div>
    
</body>
</html>

resources/views/quote/list.blade.php
@extends('quote.layout')
 
@section('content')
<div class="row mt40">
   <div class="col-md-10">
    <h2>Quotes</h2>
   </div>
   <div class="col-md-2">
    <a href="{{ route('quote.create') }}" class="btn btn-danger">Add Quote</a>
   </div>
   <br><br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Opps!</strong> Something went wrong<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
   @endif
  
    
</div>

<div class="row">
@foreach($quote as $note)
      <div class="col-md-6">
         <div class="card flex-md-row mb-4 shadow-sm h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
               <strong class="d-inline-block mb-2 text-success">{{ $note->tvshow }}</strong>
               <h6 class="mb-0">
                  <a class="text-dark" href="#">{{ $note->season }}</a>
               </h6>
               <div class="mb-1 text-muted small">{{ date('d m Y', strtotime($note->created_at)) }}</div>
               <p class="card-text mb-auto">{{ $note->content }}</p>
         
               <form action="{{ route('quote.destroy', $note->id)}}" method="post">
                  {{ csrf_field() }}
                  @method('DELETE')
                  <button class="btn btn-outline-danger btn-sm" type="submit">Delete</button>
                </form>
                <a class="btn btn-outline-success btn-sm" href="{{ route('quote.edit',$note->id)}}">Re-write</a>
            </div>
            <img class="card-img-right flex-auto d-none d-lg-block" alt="Thumbnail [200x250]" src="https://picsum.photos/seed/picsum/200/300" style="width: 200px; height: 250px;">
         </div>
      </div>
      @endforeach
   </div>

@endsection
</div>